### ISSUE TITLE
pxRRead gives inconsistent data for stattab table

### ISSUE THREAD

**Issue by cmdoret** [SDSC-ORD/pxRRead#32]
Dataset on baby names used in https://github.com/statistikZH/statbotData/pull/131 gives inconsistent values for ranks, perhaps depending on library versions

**Comment by supermaxiste** [comment]
@cmdoret I spotted this orphan task 😢 can we give it a new home or put it out of its misery 🙈

**Comment by cmdoret** [comment]
Thanks, this was an issue in the dataset itself rather than the library! We can close
